//this file keeps fonts that will be used throughout the application...

//importing Inter font from the next/font/google module as my primary font...
import { Inter } from 'next/font/google';

//using the latin subset...
export const inter = Inter({subsets: ['latin']});

//adding a secondary font...
import { Lusitana } from 'next/font/google';

//adding the french subset...
export const lusitana = Lusitana({subsets: ['latin'], weight: "700"});